# Generated by Django 5.0.6 on 2024-07-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Registro_Cliente',
        ),
    ]
